name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "デプロイするブランチ"
        required: true
        default: "feature-LocalStrage"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: Task-Manager/test/package-lock.json

      - name: Install dependencies
        working-directory: ./Task-Manager/test
        run: npm ci

      - name: Build
        working-directory: ./Task-Manager/test
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./Task-Manager/test/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5